### ISSUE TITLE
Add property 'extracts' with 'exsentences=2'

### ISSUE THREAD

**Issue by macloo** [martin-majlis/Wikipedia-API#21]
This is nicer than summary, imo, because you get to specify how many sentences you want. Jemisin has a really long summary, so you can test with with numbers greater than 2. 

More readable in browser: 
`https://en.wikipedia.org/w/api.php?action=query&prop=extracts&exintro&explaintext&exsentences=2&titles=N._K._Jemisin`

JSON version: 
`https://en.wikipedia.org/w/api.php?action=query&prop=extracts&exintro&explaintext&exsentences=2& format=json&titles=N._K._Jemisin`

**Comment by martin-majlis** [comment]
Thanks for this suggestion.

My goal was to make the API very simple - so there is no possibility now how to tune parameters passed to underlying API calls.

But I believe that both approaches could be there - one simple and the other one which allows you te exactly specify which parameters.

Goal of this issue is to be able to pass parameters from - https://en.wikipedia.org/w/api.php?action=help&modules=query%2Bextracts 

```
import sys
import wikipediaapi
wikipediaapi.log.setLevel(level=wikipediaapi.logging.DEBUG)

# Set handler if you use Python in interactive mode
out_hdlr = wikipediaapi.logging.StreamHandler(sys.stderr)
out_hdlr.setFormatter(wikipediaapi.logging.Formatter('%(asctime)s %(message)s'))
out_hdlr.setLevel(wikipediaapi.logging.DEBUG)
wikipediaapi.log.addHandler(out_hdlr)

wiki = wikipediaapi.Wikipedia('en')
page = wiki.page('N._K._Jemisin')
print(page.summary)
```

**Comment by martin-majlis** [comment]
It is possible to use this functionality in version 0.5.0

Example:

```python
import wikipediaapi
wiki = wikipediaapi.Wikipedia('en')
page = wiki.page('Python_(programming_language)')
len(wiki.extracts(page, exsentences=1))
# 75
len(wiki.extracts(page, exsentences=2))
# 234
```

If you have any other suggestions, please, let me know.

**Comment by macloo** [comment]
Amazing! Thank you!
