### ISSUE TITLE
can not seem to find subsection

### ISSUE THREAD

**Issue by chaoranxie** [martin-majlis/Wikipedia-API#6]
I am trying to parse this page https://en.wikipedia.org/wiki/Four-thousand_footers. But it seems like it can not find the list within the section "The New Hampshire list"
```
page_py = wiki_html.page('Four-thousand_footers')
section = page_py.sections[2]
section.sections
```

**Comment by martin-majlis** [comment]
I have to say, that this bug is mystery for me.

When you try those queries with logging enabled, you will see also requests to Wikipedia API.
```
import logging
logging.basicConfig(level=logging.DEBUG)
import wikipediaapi
wiki_html = wikipediaapi.Wikipedia(
	language='en',
	extract_format=wikipediaapi.ExtractFormat.HTML
)
page_1 = wiki_html.page('Four-thousand_footers')
print(page_1.sections[2])

wiki_wiki = wikipediaapi.Wikipedia(
	language='en'
)
page_2 = wiki_wiki.page('Four-thousand_footers')
print(page_2.sections[2])
```
And when I check [wiki format](http://en.wikipedia.org/w/api.php?exsectionformat=wiki&titles=Four-thousand_footers&explaintext=1&prop=extracts&action=query) or [html format](http://en.wikipedia.org/w/api.php?titles=Four-thousand_footers&explaintext=1&prop=extracts&action=query). these mountains are not there.

If you figure out, which API call will return these data, I will fix it.

**Comment by chaoranxie** [comment]
I tried other wikipedia wrapper similar result. my guess is that maybe the wikipeida page itself knows the id to the subsection and is able to get the subsection some other way via a separate api. sorry cant help much

**Comment by martin-majlis** [comment]
@chaoranxie : This is undrlying [API call](https://en.wikipedia.org/w/api.php?action=help&modules=query%2Bextracts). It is not [https://en.wikipedia.org/w/api.php?action=query&explaintext=1&exsectionformat=wiki&prop=extracts&titles=Four-thousand_footers])[there] althought I have tried different parameters.

If you will figure out how to get that part from their API, please, reopen this issue.
